
@startuml Authorization Code Flow

Actor "EndUser" as EndUser
Participant "User-Agent" as UserAgent
participant "Relaying Party" as RP
participant "IdP Authorization_endopoint" as IdP_authorization
participant "IdP Token_endopoint" as IdP_token
participant "IdP UserinfoEndpoint" as Userinfo

EndUser -> RP: 1. Request Authorization\nGET /connect/authorize\n{client_id, scope, response_type=code, redirect_uri, state, nonce, prompt}
RP -> EndUser: 2. Redirect to IdP Authorization\nStatus:302\n{client_id, scope, response_type=code, redirect_uri, state, nonce, prompt}
EndUser -> IdP_authorization: 3. Request Authorization\n{client_id, scope, response_type=code, redirect_uri, state, nonce, prompt}
IdP_authorization -> EndUser: 4. Request Credential
EndUser -> IdP_authorization: 5. Login\n{email, password}
IdP_authorization -> EndUser: 4. Request Permission & chekgin RP
EndUser -> IdP_authorization: 5. Permit\n{utf8=✔︎, authenticity_token, response_type, client_id, scope, prompt=login, redirect_uri, state, nonce}
IdP_authorization -> EndUser: 6. Authorization Code\n{code, redirect_uri}
EndUser -> RP: 7. Redirect to RP\n{code, redirect_uri}
RP -> IdP_token: 8. \nheder: {client_id, client_secret}\nbody:{grant_type, code, redirect_uri}
IdP_token -> RP: 9. Token\n{access_token, id_token, refresh_token}
RP -> Userinfo: 10. Request Access\nheader: {access_token}
Userinfo -> RP: 11. Userinfo\n{sub, name, email}
@enduml